name: add to project factory dependabot

on:
  pull_request:
    branches: [main]

jobs:
  add-to-project-dependabot:
    permissions:
      repository-projects: write
    secrets:
      SENZING_GITHUB_PROJECT_RW_TOKEN: ${{ secrets.SENZING_GITHUB_PROJECT_RW_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/add-to-project-dependabot.yaml@v1
    with:
      project: ${{ vars.SENZING_PROJECT_FACTORY }}
